/** @deprecated Import from ./types/index.js instead. */
export {
  VocabularyValidationError,
  workspaceId,
  stakeholderId,
  branchId,
  ideaLabel,
  suggestionId,
  feedbackItemId,
  artifactId,
  notificationId,
  generatedContextId,
  inWorkspace,
  humanActor,
  delegatedActor,
  isHumanActor,
  isDelegatedActor,
} from './types/index.js';

export type {
  WorkspaceId,
  StakeholderId,
  BranchId,
  IdeaLabel,
  SuggestionId,
  FeedbackItemId,
  ArtifactId,
  NotificationId,
  GeneratedContextId,
  Discipline,
  ChunkType,
  ContextKind,
  RelationshipType,
  ChunkLifecycleState,
  ChunkActivityState,
  BranchState,
  SuggestionState,
  EdgeState,
  ActorKind,
  ActorContext,
  HumanActorContext,
  DelegatedActorContext,
  WorkspaceScoped,
} from './types/index.js';
