/**
 * Postgres-backed persistence adapter for evaluation feedback,
 * verification signals, and the notification records that route them to
 * stakeholders (story S09).
 *
 * Sources of authority:
 * - Story S09: a stakeholder can see verification feedback attached to the
 *   branch it evaluated (AC1); the author of an evaluated branch, at
 *   minimum, is notified immediately upon ingestion regardless of online
 *   status (AC2); acknowledging a notification never loses the historical
 *   feedback/signal record it references (AC3); recording feedback/signals
 *   never itself changes a branch's lifecycle state (AC4); a verification
 *   signal or feedback record is attributed to an authenticated stakeholder,
 *   never a client-supplied actor claim (AC5).
 * - Technical spec §"Feedback notification routing" (`IDEA-67`, `IDEA-68`):
 *   feedback/signals routed and persisted as notification records
 *   immediately upon ingestion; author notified at minimum.
 * - Technical spec §"Notification acknowledgement is non-destructive":
 *   acknowledging must not delete or mutate the underlying feedback/signal
 *   record it references — `acknowledgeNotification` below only ever
 *   updates `notifications.acknowledged_at`.
 * - Technical spec §"Protected operation contracts": persisted records must
 *   retain enough provenance to attribute a signal/feedback item to a human
 *   stakeholder; this adapter never accepts a raw stakeholder id for
 *   authorship of a `FeedbackItem`/`VerificationSignal` — both are only
 *   constructible via `recordFeedbackItem`/`recordVerificationSignal`,
 *   which take the id from an authenticated `ActorContext`. Likewise, the
 *   "author must be notified" recipient (AC2) is resolved here from the
 *   durably stored `branches.author_stakeholder_id` column — never from a
 *   caller-supplied recipient claim (see `schema.ts`'s
 *   `MIGRATE_BRANCHES_AUTHOR` doc header for the full rationale, added
 *   after rubber-duck review flagged caller-supplied author routing as a
 *   spoofing/misrouting risk).
 * - Technical spec §"Tenant isolation": every method takes a `workspaceId`
 *   and every SQL predicate filters on it explicitly.
 * - Technical spec §"Required domain error categories": failures map to
 *   existing `BranchLifecycleError('not-found')` (missing/foreign-workspace
 *   branch) or the new `NotificationError` (reusing `'not-found'`,
 *   `'invalid-state-transition'` for a duplicate feedback/signal/notification
 *   identity, and `'tenant-boundary-violation'` — no new category is
 *   introduced).
 * - nestjs-security skill: parameterized queries only, never string
 *   concatenation.
 *
 * Notification ids are generated by this adapter (`randomUUID`, wrapped by
 * `notificationId()`), not supplied by the caller: the recipient set for a
 * submission is only fully known once the branch's durable author is read
 * from the database inside the same transaction, so a caller cannot know in
 * advance how many notification ids it would need to provide.
 */

import { randomUUID } from 'node:crypto';
import { Inject, Injectable } from '@nestjs/common';
import { DatabaseError, type Pool, type PoolClient } from 'pg';
import { BranchLifecycleError } from '../domain/branch-lifecycle.js';
import {
  NotificationError,
  notificationId,
  resolveNotificationRecipients,
  type ActorKind,
  type BranchId,
  type FeedbackItem,
  type FeedbackItemId,
  type NotificationId,
  type NotificationSource,
  type StakeholderId,
  type VerificationOutcome,
  type VerificationSignal,
  type VerificationSignalId,
  type WorkspaceId,
} from '../domain/types/index.js';
import { PG_POOL } from './database-pool.provider.js';

/** Postgres SQLSTATE for a foreign-key-constraint violation. */
const FOREIGN_KEY_VIOLATION = '23503';

/** Postgres SQLSTATE for a unique-constraint violation. */
const UNIQUE_VIOLATION = '23505';

export interface PersistedFeedbackItem {
  readonly workspaceId: WorkspaceId;
  readonly branchId: BranchId;
  readonly feedbackItemId: FeedbackItemId;
  readonly authoredByStakeholderId: StakeholderId;
  readonly authoredByActorKind: ActorKind;
  readonly submittedAt: string;
  readonly content: string;
}

export interface PersistedVerificationSignal {
  readonly workspaceId: WorkspaceId;
  readonly branchId: BranchId;
  readonly signalId: VerificationSignalId;
  readonly outcome: VerificationOutcome;
  readonly reportedByStakeholderId: StakeholderId;
  readonly reportedByActorKind: ActorKind;
  readonly reportedAt: string;
  readonly summary: string;
}

export interface PersistedNotification {
  readonly workspaceId: WorkspaceId;
  readonly branchId: BranchId;
  readonly notificationId: NotificationId;
  readonly recipientStakeholderId: StakeholderId;
  readonly source: NotificationSource;
  readonly createdAt: string;
  readonly acknowledgedAt?: string;
}

/**
 * Additional stakeholders (beyond the branch's durable author, which this
 * adapter always resolves and notifies itself) relevant to one ingestion
 * event. Technical spec §"Feedback notification routing": "other relevant
 * stakeholders may also be notified" — deciding who those are is a
 * higher-layer concern; this adapter only guarantees they are included
 * alongside the mandatory author.
 */
export interface AdditionalNotificationRecipients {
  readonly additionalStakeholderIds?: StakeholderId[];
}

export interface SubmissionResult<TSource> {
  readonly record: TSource;
  readonly notifications: PersistedNotification[];
}

interface FeedbackItemRow {
  readonly workspace_id: string;
  readonly branch_id: string;
  readonly feedback_item_id: string;
  readonly authored_by_stakeholder_id: string;
  readonly authored_by_actor_kind: string;
  readonly submitted_at: string | Date;
  readonly content: string;
}

interface VerificationSignalRow {
  readonly workspace_id: string;
  readonly branch_id: string;
  readonly signal_id: string;
  readonly outcome: string;
  readonly reported_by_stakeholder_id: string;
  readonly reported_by_actor_kind: string;
  readonly reported_at: string | Date;
  readonly summary: string;
}

interface NotificationRow {
  readonly workspace_id: string;
  readonly branch_id: string;
  readonly notification_id: string;
  readonly recipient_stakeholder_id: string;
  readonly source_kind: string;
  readonly source_id: string;
  readonly created_at: string | Date;
  readonly acknowledged_at: string | Date | null;
}

const FEEDBACK_ITEM_COLUMNS = `workspace_id, branch_id, feedback_item_id, authored_by_stakeholder_id,
       authored_by_actor_kind, submitted_at, content`;

const VERIFICATION_SIGNAL_COLUMNS = `workspace_id, branch_id, signal_id, outcome,
       reported_by_stakeholder_id, reported_by_actor_kind, reported_at, summary`;

const NOTIFICATION_COLUMNS = `workspace_id, branch_id, notification_id, recipient_stakeholder_id,
       source_kind, source_id, created_at, acknowledged_at`;

function toIsoString(value: string | Date): string {
  return value instanceof Date ? value.toISOString() : value;
}

function isForeignKeyViolation(error: unknown): boolean {
  return error instanceof DatabaseError && error.code === FOREIGN_KEY_VIOLATION;
}

function isUniqueViolation(error: unknown): boolean {
  return error instanceof DatabaseError && error.code === UNIQUE_VIOLATION;
}

function rowToFeedbackItem(row: FeedbackItemRow): PersistedFeedbackItem {
  return {
    workspaceId: row.workspace_id as WorkspaceId,
    branchId: row.branch_id as BranchId,
    feedbackItemId: row.feedback_item_id as FeedbackItemId,
    authoredByStakeholderId: row.authored_by_stakeholder_id as StakeholderId,
    authoredByActorKind: row.authored_by_actor_kind as ActorKind,
    submittedAt: toIsoString(row.submitted_at),
    content: row.content,
  };
}

function rowToVerificationSignal(row: VerificationSignalRow): PersistedVerificationSignal {
  return {
    workspaceId: row.workspace_id as WorkspaceId,
    branchId: row.branch_id as BranchId,
    signalId: row.signal_id as VerificationSignalId,
    outcome: row.outcome as VerificationOutcome,
    reportedByStakeholderId: row.reported_by_stakeholder_id as StakeholderId,
    reportedByActorKind: row.reported_by_actor_kind as ActorKind,
    reportedAt: toIsoString(row.reported_at),
    summary: row.summary,
  };
}

function rowToNotificationSource(row: NotificationRow): NotificationSource {
  return row.source_kind === 'feedback-item'
    ? { kind: 'feedback-item', feedbackItemId: row.source_id as FeedbackItemId }
    : { kind: 'verification-signal', signalId: row.source_id as VerificationSignalId };
}

function rowToNotification(row: NotificationRow): PersistedNotification {
  const base: PersistedNotification = {
    workspaceId: row.workspace_id as WorkspaceId,
    branchId: row.branch_id as BranchId,
    notificationId: row.notification_id as NotificationId,
    recipientStakeholderId: row.recipient_stakeholder_id as StakeholderId,
    source: rowToNotificationSource(row),
    createdAt: toIsoString(row.created_at),
  };
  return row.acknowledged_at == null ? base : { ...base, acknowledgedAt: toIsoString(row.acknowledged_at) };
}

@Injectable()
export class NotificationRepository {
  constructor(@Inject(PG_POOL) private readonly pool: Pool) {}

  /**
   * Persists an evaluation feedback item and routes a notification to the
   * branch's durable author plus any additional relevant stakeholders, all
   * inside one transaction (AC1, AC2). Throws
   * `BranchLifecycleError('not-found')` if the branch is not registered in
   * this workspace, and `NotificationError('not-found')` if the branch has
   * no recorded author (a branch registered before story S09's
   * `author_stakeholder_id` migration, or via a code path that omitted it).
   */
  async submitFeedbackItem(
    feedback: FeedbackItem,
    recipients: AdditionalNotificationRecipients = {},
  ): Promise<SubmissionResult<PersistedFeedbackItem>> {
    return this.submit(
      feedback.workspaceId,
      feedback.branchId,
      { kind: 'feedback-item', feedbackItemId: feedback.feedbackItemId },
      recipients,
      async (client) => {
        const result = await client.query<FeedbackItemRow>(
          `INSERT INTO feedback_items (workspace_id, branch_id, feedback_item_id, authored_by_stakeholder_id, authored_by_actor_kind, submitted_at, content)
           VALUES ($1, $2, $3, $4, $5, $6, $7)
           RETURNING ${FEEDBACK_ITEM_COLUMNS}`,
          [
            feedback.workspaceId,
            feedback.branchId,
            feedback.feedbackItemId,
            feedback.authoredByStakeholderId,
            feedback.authoredByActorKind,
            feedback.submittedAt,
            feedback.content,
          ],
        );
        return rowToFeedbackItem(result.rows[0]!);
      },
    );
  }

  /**
   * Persists a verification signal and routes a notification to the
   * branch's durable author plus any additional relevant stakeholders, all
   * inside one transaction (AC1, AC2). Same error mapping as
   * `submitFeedbackItem`.
   */
  async submitVerificationSignal(
    signal: VerificationSignal,
    recipients: AdditionalNotificationRecipients = {},
  ): Promise<SubmissionResult<PersistedVerificationSignal>> {
    return this.submit(
      signal.workspaceId,
      signal.branchId,
      { kind: 'verification-signal', signalId: signal.signalId },
      recipients,
      async (client) => {
        const result = await client.query<VerificationSignalRow>(
          `INSERT INTO verification_signals (workspace_id, branch_id, signal_id, outcome, reported_by_stakeholder_id, reported_by_actor_kind, reported_at, summary)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
           RETURNING ${VERIFICATION_SIGNAL_COLUMNS}`,
          [
            signal.workspaceId,
            signal.branchId,
            signal.signalId,
            signal.outcome,
            signal.reportedByStakeholderId,
            signal.reportedByActorKind,
            signal.reportedAt,
            signal.summary,
          ],
        );
        return rowToVerificationSignal(result.rows[0]!);
      },
    );
  }

  private async submit<TSource>(
    workspaceId: WorkspaceId,
    branchId: BranchId,
    source: NotificationSource,
    recipients: AdditionalNotificationRecipients,
    insertSource: (client: PoolClient) => Promise<TSource>,
  ): Promise<SubmissionResult<TSource>> {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');

      // Resolve the branch's durable author from storage — never from a
      // caller-supplied recipient claim (see module doc header).
      const branchResult = await client.query<{ author_stakeholder_id: string | null }>(
        `SELECT author_stakeholder_id FROM branches WHERE workspace_id = $1 AND branch_id = $2 FOR UPDATE`,
        [workspaceId, branchId],
      );
      const branchRow = branchResult.rows[0];
      if (!branchRow) {
        throw new BranchLifecycleError(
          'not-found',
          `branch '${branchId}' is not registered in workspace '${workspaceId}'`,
        );
      }
      if (!branchRow.author_stakeholder_id) {
        throw new NotificationError(
          'not-found',
          `branch '${branchId}' in workspace '${workspaceId}' has no recorded author; cannot route a notification`,
        );
      }
      const authorStakeholderId = branchRow.author_stakeholder_id as StakeholderId;

      const record = await insertSource(client);

      const recipientStakeholderIds = resolveNotificationRecipients(
        authorStakeholderId,
        recipients.additionalStakeholderIds ?? [],
      );

      const notifications: PersistedNotification[] = [];
      for (const recipientStakeholderId of recipientStakeholderIds) {
        const sourceId = source.kind === 'feedback-item' ? source.feedbackItemId : source.signalId;
        const result = await client.query<NotificationRow>(
          `INSERT INTO notifications (workspace_id, branch_id, notification_id, recipient_stakeholder_id, source_kind, source_id)
           VALUES ($1, $2, $3, $4, $5, $6)
           RETURNING ${NOTIFICATION_COLUMNS}`,
          [workspaceId, branchId, notificationId(randomUUID()), recipientStakeholderId, source.kind, sourceId],
        );
        notifications.push(rowToNotification(result.rows[0]!));
      }

      await client.query('COMMIT');
      return { record, notifications };
    } catch (error) {
      await this.rollbackQuietly(client);
      if (isForeignKeyViolation(error)) {
        throw new BranchLifecycleError(
          'not-found',
          `branch '${branchId}' is not registered in workspace '${workspaceId}'`,
        );
      }
      if (isUniqueViolation(error)) {
        throw new NotificationError(
          'invalid-state-transition',
          `a feedback item, verification signal, or notification with this identity is already persisted in workspace '${workspaceId}'`,
        );
      }
      throw error;
    } finally {
      client.release();
    }
  }

  /** AC1: every feedback item recorded against a branch, oldest first. */
  async listFeedbackItemsForBranch(
    workspaceId: WorkspaceId,
    branchId: BranchId,
  ): Promise<PersistedFeedbackItem[]> {
    const result = await this.pool.query<FeedbackItemRow>(
      `SELECT ${FEEDBACK_ITEM_COLUMNS} FROM feedback_items
       WHERE workspace_id = $1 AND branch_id = $2
       ORDER BY submitted_at, feedback_item_id`,
      [workspaceId, branchId],
    );
    return result.rows.map(rowToFeedbackItem);
  }

  /** AC1: every verification signal recorded against a branch, oldest first. */
  async listVerificationSignalsForBranch(
    workspaceId: WorkspaceId,
    branchId: BranchId,
  ): Promise<PersistedVerificationSignal[]> {
    const result = await this.pool.query<VerificationSignalRow>(
      `SELECT ${VERIFICATION_SIGNAL_COLUMNS} FROM verification_signals
       WHERE workspace_id = $1 AND branch_id = $2
       ORDER BY reported_at, signal_id`,
      [workspaceId, branchId],
    );
    return result.rows.map(rowToVerificationSignal);
  }

  /** AC2/AC3: every notification routed to a stakeholder, newest first. */
  async listNotificationsForStakeholder(
    workspaceId: WorkspaceId,
    recipientStakeholderId: StakeholderId,
  ): Promise<PersistedNotification[]> {
    const result = await this.pool.query<NotificationRow>(
      `SELECT ${NOTIFICATION_COLUMNS} FROM notifications
       WHERE workspace_id = $1 AND recipient_stakeholder_id = $2
       ORDER BY created_at DESC, notification_id`,
      [workspaceId, recipientStakeholderId],
    );
    return result.rows.map(rowToNotification);
  }

  /**
   * Acknowledges a notification (AC3). Only ever updates
   * `notifications.acknowledged_at` — never touches `feedback_items` or
   * `verification_signals` — and is idempotent via `COALESCE`: the first
   * acknowledgement timestamp sticks, a repeat call is a harmless no-op
   * rather than overwriting it with a later time.
   *
   * Throws `NotificationError('not-found')` if no notification with this id
   * exists in this workspace.
   */
  async acknowledgeNotification(
    workspaceId: WorkspaceId,
    notification: NotificationId,
    acknowledgedAt: string,
  ): Promise<PersistedNotification> {
    const result = await this.pool.query<NotificationRow>(
      `UPDATE notifications
       SET acknowledged_at = COALESCE(acknowledged_at, $3)
       WHERE workspace_id = $1 AND notification_id = $2
       RETURNING ${NOTIFICATION_COLUMNS}`,
      [workspaceId, notification, acknowledgedAt],
    );
    const row = result.rows[0];
    if (!row) {
      throw new NotificationError(
        'not-found',
        `notification '${notification}' does not exist in workspace '${workspaceId}'`,
      );
    }
    return rowToNotification(row);
  }

  private async rollbackQuietly(client: PoolClient): Promise<void> {
    try {
      await client.query('ROLLBACK');
    } catch {
      // Connection is already broken (e.g. the BEGIN itself failed); the
      // pool will discard it on release. Swallowing here preserves the
      // original error thrown from the try block above.
    }
  }
}
